CREATE SEQUENCE city_id_seq;
CREATE TABLE CITIES(
  id INTEGER NOT NULL DEFAULT nextval(city_id_seq) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  postalcode VARCHAR(255) NOT NULL,
  idcountry INTEGER REFERENCES COUNTRIES(ID)
);
ALTER SEQUENCE city_id_seq OWNED BY CITIES.ID;
